# Generated by Django 4.2.27 on 2026-01-08 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(help_text='Kod kraju producenta, np. PL, IT, FR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Krótki opis kategorii.')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('description', models.TextField(blank=True, help_text='Opis Produktu')),
                ('gender', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna'), ('N', 'Nijaki')], default='N', max_length=1)),
                ('size', models.IntegerField(choices=[(1, 'Xs'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'Xl'), (6, 'Xxl')], default=3)),
                ('fabric', models.CharField(choices=[('C', 'Bawełna (Cotton)'), ('P', 'Poliester'), ('L', 'Len'), ('S', 'Jedwab (Silk)')], default='C', max_length=1)),
                ('colors', models.CharField(choices=[('C', 'Czarny'), ('B', 'Biały'), ('N', 'Niebieski'), ('Z', 'Zielony')], default='B', max_length=1)),
                ('stock_count', models.PositiveIntegerField(default=1, help_text='Ilość sztuk w magazynie.')),
                ('sale', models.BooleanField(default=False, help_text='Czy produkt jest na wyprzedaży?')),
                ('price', models.DecimalField(decimal_places=2, help_text='Cena w PLN', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
