# Generated by Django 4.2.27 on 2026-01-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(choices=[('C', 'Czarny'), ('B', 'Biały'), ('N', 'Niebieski'), ('Z', 'Zielony'), ('R', 'Czerwony'), ('G', 'Szary')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(choices=[('C', 'Bawełna (Cotton)'), ('P', 'Poliester'), ('L', 'Len'), ('S', 'Jedwab (Silk)'), ('W', 'Wełna (Wool)'), ('J', 'Jeans (Denim)'), ('K', 'Skóra (Leather)'), ('E', 'Elastan (Elastane)')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('35-38', '35-38'), ('39-42', '39-42'), ('43-46', '43-46'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36')], default='M', max_length=10),
        ),
    ]
