# Generated by Django 4.2.27 on 2026-01-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('waiting', 'Oczekujące na wpłatę'), ('processing', 'W realizacji'), ('shipped', 'Wysłane'), ('delivered', 'Dostarczone'), ('cancelled', 'Anulowane')], default='waiting', max_length=20),
        ),
    ]
